export const experiences = [
    {
        title: "Master of Science in Computer Science",
        company_name: "SANTA CLARA UNIVERSITY",
        icon: './scu.png',
        link: "https://www.scu.edu/",
        iconBg: "#fff",
        date: "June 2025",
        points: [
            "Graduating on 14th June 2025.",
        ],
    },
    {
        title: "Software Engineer Intern",
        company_name: "F5, INC",
        icon: './f5.png',
        iconBg: "#fff",
        link: "https://www.f5.com/",
        date: "July 2024 - Sept 2024",
        points: [
            "Built an AI-powered chatbot for F5’s Central Manager using a custom RAG architecture with Azure OpenAI and Postgres vector store, enabling AI Ops, automated workflows, document validation, and developer assistance.",
            "Developed the chatbot frontend with React, Typescript, and integrated with backend services using FastAPIs.",
            "Improved BIG-IP SSLO forward proxy with JA4+ TLS fingerprinting by fixing TCL iRules in outbound gateway.",
            "Set up BIG-IP SSL Orchestrator on AWS and conducted manual and automated tests using GitLab, REST client, Kubernetes, and Wireshark.",
        ],
    },
    {
        title: "Master of Science in Computer Science",
        company_name: "SANTA CLARA UNIVERSITY",
        icon: './scu.png',
        iconBg: "#fff",
        link: "https://www.scu.edu/",
        date: "Sept 2023",
        points: [
            "Started my Masters in Computer Science at Santa Clara University.",
            "Interesting coursework I studied: Design and Analysis of Algorithms, Distributed Systems, Machine Learning, Advanced Operating Systems, Computer Architecture, Object-Oriented Analysis & Design, Software Engineering",
        ],
    },
    {
        title: "Software Engineer",
        company_name: "SIEMENS",
        icon: './siemens.png',
        iconBg: "#fff",
        link: "https://www.siemens.com/",
        date: "March 2023 - July 2023",
        points: [
            "Architected Perl automation scripts based on Functional Test Specification Documents to test wayside and onboard equipment of the Communications Based Train Control (CBTC) System.",
            "Executed and debugged tests within the SPA simulator on Unix. Reported critical bugs in the simulator through detailed log analysis and troubleshooting.",
            "Performed code reviews on Collaborator and conducted code coverage analysis on Ada source code using GNAT.",
        ],
    },
    {
        title: "Senior Software Engineer",
        company_name: "PERSISTENT SYSTEMS",
        icon: './persistent.png',
        iconBg: "#fff",
        link: "https://www.persistent.com/",
        date: "Nov 2020 - Jan 2023",
        points: [
            "Engineered Python scripts for automation testing of Rovius Cloud Platform powered by Apache CloudStack.",
            "Automated the IaaS server installation and configuration using Shell scripts, reducing manual effort by 95%.",
            "Enhanced Jenkins-based automation framework and resolved issues in component/integration test pipelines, reducing framework-related test failures to under 2%.",
            "Developed performance test suites for bulk operations and conducted performance tests across platform versions benchmarking API response times and database throughput.",
            "Collaborated with the DevOps team to configure CI/CD infrastructure on new servers and fix pipeline issues.",
            "Designed and executed comprehensive test strategies for cloud infrastructure features - virtual machines, networks, storage, hypervisors (VMware, KVM, XenServer), load balancers, and Kubernetes clusters.",
        ],
    },
];